### ISSUE TITLE
update dependencies in import_map/deno.json

### ISSUE THREAD

**Issue by sigmaSd** [hasundue/deno-molt#18]
Can dependencies in deno.json/import_map.json be updated ?

This use-case is a frequent one if you consider frameworks like https://github.com/denoland/fresh

**Comment by hasundue** [comment]
Yes, it's supposed to do it. Doesn't it work for you? Or maybe we should make it clearer in the documentation.

**Comment by sigmaSd** [comment]
ah I see I did `molt deno.json` it said no update found, I need to point it to the actual java script entry point

I think the error is confusing though, maybe we should hardcore an error if the user tries to use deno.json/import_map as an entry point or actually  any non js/ts file maybe

**Comment by sigmaSd** [comment]
I added a commit for this here https://github.com/hasundue/deno-molt/pull/17

**Comment by hasundue** [comment]
Solved with #17 I believe.
Thanks for pointing it out.
